services:
  video-processor:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - DEEPGRAM_API_KEY=${DEEPGRAM_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
