"""
Video Topic Splitter - A tool for segmenting videos based on topic analysis.
Code generated by Claude (Anthropic) based on user specifications and requirements.
"""

from setuptools import find_packages, setup

setup(
    name="video_topic_splitter",
    version="0.2.0",  # Increased version number to 0.2.0
    description="AI-generated tool for topic-based video segmentation",
    long_description="""
    This package was generated by Claude (Anthropic) based on user specifications.
    It combines audio processing, transcription, topic modeling, and AI analysis
    to intelligently segment videos based on content.
    """,
    author="Generated by Claude (Anthropic)",
    author_email="your_email@example.com",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    include_package_data=True,
    install_requires=[
        "python-dotenv>=1.0.0",
        "openai>=1.12.0",
        "google-generativeai>=0.4.3",
        "requests>=2.31.0",
        "pydub>=0.25.1",
        "moviepy>=1.0.3",
        "pyaudio",
        "scenedetect[opencv]>=0.6.2",
        "imagehash>=4.3.1",
        "videogrep>=2.0.0",
        "ffmpeg-normalize",
        "unsilence>=0.4.2",
        "scikit-learn>=1.4.1",
        "nltk>=3.8.1",
        "progressbar2>=4.2.0",
        "Pillow>=10.2.0",
        "yt-dlp>=2024.3.24",
        "pytesseract>=0.3.10",
        "opencv-python>=4.8.0",
        "numpy>=1.24.0",
    ],
    entry_points={
        "console_scripts": [
            "video-topic-splitter=video_topic_splitter.cli:main",
        ],
    },
    python_requires=">=3.8",
)
