"""
Video Topic Splitter - A tool for segmenting videos based on topic analysis.
Code generated by Claude (Anthropic) based on user specifications and requirements.
"""

from setuptools import find_packages, setup

setup(
    name="video_topic_splitter",
    version="0.1.0",
    description="AI-generated tool for topic-based video segmentation",
    long_description="""
    This package was generated by Claude (Anthropic) based on user specifications.
    It combines audio processing, transcription, topic modeling, and AI analysis
    to intelligently segment videos based on content.
    """,
    author="Generated by Claude (Anthropic)",
    author_email="your_email@example.com",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    include_package_data=True,
    install_requires=[
        "python-dotenv",
        "deepgram-sdk",
        "groq",
        "pydub",
        "spacy",
        "gensim",
        "videogrep",
        "moviepy",
        "progressbar2",
        "google-generativeai",
        "Pillow",
    ],
    entry_points={
        "console_scripts": [
            "video-topic-splitter=video_topic_splitter.cli:main",
        ],
    },
    python_requires=">=3.8",
)
