"""
Video Topic Splitter - A tool for segmenting videos based on topic analysis.
Code generated by Claude (Anthropic) based on user specifications and requirements.
"""

from setuptools import find_packages, setup

setup(
    name="video_topic_splitter",
    version="0.2.0",  # Increased version number to 0.2.0
    description="AI-generated tool for topic-based video segmentation",
    long_description="""
    This package was generated by Claude (Anthropic) based on user specifications.
    It combines audio processing, transcription, topic modeling, and AI analysis
    to intelligently segment videos based on content.
    """,
    author="Generated by Claude (Anthropic)",
    author_email="your_email@example.com",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    include_package_data=True,
    install_requires=[
        "python-dotenv>=1.0.0",
        "deepgram-sdk>=2.12.0",
        "groq>=0.4.0",
        "pydub>=0.25.1",
        "moviepy",
        "openai>=1.12.0",  # Corrected version to match requirements.txt
        "google-generativeai>=0.4.3",  # Corrected version to match requirements.txt
        "videogrep>=2.0.0",  # Corrected version to match requirements.txt
        "ffmpeg-python>=0.2.0",  # Added explicit version
        "ffmpeg-normalize",  # Added as it's used
        "unsilence>=0.4.2",  # Added explicit version
        "scikit-learn>=1.4.1",  # Added explicit version
        "nltk>=3.8.1",  # Added explicit version
        "progressbar2>=4.2.0",  # Corrected version to match requirements.txt
        "moviepy>=1.0.3",  # Corrected version to match requirements.txt
        "Pillow>=10.2.0",  # Corrected version to match requirements.txt
        "yt-dlp>=2024.3.24",  # Corrected version to match requirements.txt
        "pytesseract>=0.3.10",  # Corrected version to match requirements.txt
        "opencv-python>=4.8.0",  # Added explicit version
        "numpy>=1.24.0",  # Added explicit version
        "openrouter>=0.3.0",  # Added explicit version
    ],
    entry_points={
        "console_scripts": [
            "video-topic-splitter=video_topic_splitter.cli:main",
        ],
    },
    python_requires=">=3.8",
)
