# api/gemini.py
#!/usr/bin/env python3
"""
Gemini API integration for multimodal analysis.

This module provides a simple interface to the Google Gemini API, allowing
for the analysis of text prompts and images. It handles API key configuration
and the construction of requests to the Gemini model.
"""

import os

import google.generativeai as genai
from dotenv import load_dotenv

load_dotenv()

# Configure Gemini
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))


def analyze_with_gemini(prompt, image=None):
    """
    Analyze a prompt and optional image using the Google Gemini API.

    This function sends the provided prompt and image (if any) to the Gemini
    generative model and returns the resulting text response.

    Args:
        prompt (str): The text prompt for the analysis.
        image (PIL.Image, optional): An image to be included in the analysis.
            Defaults to None.

    Returns:
        str: The text response generated by the Gemini model.

    Raises:
        ValueError: If the GEMINI_API_KEY environment variable is not set.
    """
    if not os.getenv("GEMINI_API_KEY"):
        raise ValueError("GEMINI_API_KEY environment variable is not set")

    model = genai.GenerativeModel("gemini-2.0-flash")
    if image:
        response = model.generate_content([prompt, image])
    else:
        response = model.generate_content(prompt)
    return response.text
