# api/gemini.py
#!/usr/bin/env python3
"""Gemini API integration for video analysis."""

import os
from typing import Optional

import google.generativeai as genai
from google.generativeai.types import ContentDict, GenerationResponse # More specific types
from PIL.Image import Image # Assuming PIL Image type if image is passed
from dotenv import load_dotenv

load_dotenv()

# Configure Gemini - Consider moving this configuration into a function or class
# to avoid running it at import time and allow for more flexible key management.
try:
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("Warning: GEMINI_API_KEY environment variable not found.")
        # Depending on usage, you might want to raise an error here immediately
        # or allow configuration later.
    else:
        genai.configure(api_key=api_key)
except Exception as e:
    print(f"Error configuring Gemini API: {e}")
    # Handle configuration errors appropriately


def analyze_with_gemini(prompt: str, image: Optional[Image] = None) -> str:
    """Analyzes text or text and image content using the Google Gemini API.

    This function sends a prompt, optionally accompanied by an image, to the
    configured Gemini model ('gemini-2.0-flash-exp' currently) and returns the
    generated text response.

    Args:
        prompt: The text prompt to send to the Gemini model.
        image: An optional PIL Image object to include with the prompt for
               multimodal analysis. Defaults to None.

    Returns:
        The text content generated by the Gemini model in response to the prompt
        (and image, if provided).

    Raises:
        ValueError: If the GEMINI_API_KEY environment variable was not set during
                    initial configuration or if the genai module is not configured.
        google.api_core.exceptions.GoogleAPIError: If the API call fails for reasons
                                                  such as invalid API key, quota issues,
                                                  or server errors.
        Exception: For any other unexpected errors during the API call.

    Example:
        >>> # Text-only analysis
        >>> text_response = analyze_with_gemini("Explain the concept of recursion.")
        >>> print(text_response)

        >>> # Multimodal analysis (assuming 'my_image' is a PIL Image object)
        >>> try:
        ...     from PIL import Image
        ...     img = Image.open("path/to/your/image.jpg") # Replace with actual path
        ...     image_response = analyze_with_gemini("Describe this image.", image=img)
        ...     print(image_response)
        ... except FileNotFoundError:
        ...     print("Image file not found.")
        ... except Exception as e:
        ...     print(f"An error occurred: {e}")
    """
    # Check if the API key was successfully configured earlier
    if not genai.config or not genai.config.api_key:
         # More specific check than just os.getenv again
        raise ValueError(
            "Gemini API key is not configured. Ensure GEMINI_API_KEY is set."
            )

    # Consider making the model name configurable or a parameter
    model = genai.GenerativeModel("gemini-2.0-flash-exp") # TODO: Update model name if needed

    try:
        content: list[ContentDict | Image | str]
        if image:
            # Ensure the order is generally text then image for multimodal models
            content = [prompt, image]
        else:
            content = [prompt]

        response: GenerationResponse = model.generate_content(content)
        # Add basic error handling for the response object itself
        if not response.candidates:
             # Handle cases where the model didn't generate any response candidates
             # This might happen due to safety settings or other issues.
             safety_ratings = getattr(response, 'prompt_feedback', {}).get('safety_ratings', 'N/A')
             print(f"Warning: Gemini model did not return candidates. Prompt feedback: {safety_ratings}")
             # Decide what to return or raise here. Returning empty string for now.
             return ""

        # Accessing text safely
        return response.text

    except Exception as e:
        # Catching potential API errors and other exceptions
        print(f"Error during Gemini API call: {str(e)}")
        # Re-raise the exception to allow higher-level error handling
        raise

